---
title-prefix: "ベイズ統計モデリング-R,JAGS,Stanによるチュートリアル- 原著第2版 サポートサイト"
pagetitle: "このサイトについて"
output:
  html_document:
    toc: false
---

最終更新: `r format(Sys.time(),'%Y/%m/%d')`

## 概要

本サイトは，共立出版から発売されている「[ベイズ統計モデリング-R,JAGS,Stanによるチュートリアル- 原著第2版](http://www.kyoritsu-pub.co.jp/bookdetail/9784320113169)」のサポートサイトです。

主に以下のようなコンテンツを展開しております:

[正誤表](errata.html)

: 発売後に確認されたミスについてまとめています

[エクササイズ](exercise.html)

: 各章末にあるエクササイズについて紹介します(準備中)

[コード](code.html)

: 本書で使用しているサンプルコードへのリンク先などを紹介しています

運用に関しては，上記書籍の監訳を中心としたメンバーで行っております。

## お問い合わせについて{#contact}

### 書籍の内容に関するお問い合わせ

本書をお読みいただいて，気になった点(誤訳やtypo，内容的に気になるところなど)がございましたら，どうぞ遠慮なくお問い合わせください。

GitHubのissueから

: [本サイトのGitHubリポジトリにあるissue](https://github.com/kazutan/DBDA2E-ja/issues)よりお問い合わせいただくと，一番早くかつスムーズに対応できます。
なお，ここでの質問はGitHubの性質上webでオープンとなりますので，その点はご了承ください。

Twitterから

: 書籍専用のTwitterアカウントは存在しませんが，「[#犬4匹本](https://twitter.com/search?q=%23%E7%8A%AC4%E5%8C%B9%E6%9C%AC)」というハッシュタグがついたツイートについてはチェックするようにしています。なのでこのハッシュタグを付けてもらえれば私たちもチェックいたします。  
もしくは，監訳である前田([kazutan](https://twitter.com/kazutan))もしくは小杉([kosugitti](https://twitter.com/kosugitti))までメンションおよびDMでお問い合わせいただいてもOKです。

Mailから

: 監訳の前田までmailしていただければ，追って対応させていただきます(kazumあっとhijiyama-u.ac.jp, "あっと"はアットマークに変換してください)。ただ，対応に多少遅れることがあります...どうかご理解をお願いいたします。

他にも，訳者へ伝達できる方法(直接伝える，紙のメモを渡すなど)がありましたら，それでも構いませんのでご連絡ください。**訳者一同お待ちしております**。

### サポートサイトの内容に関するお問い合わせ 

このサポートサイトの内容について，気になる点や要望・リクエストなどありましたら遠慮なくお問い合わせください。例えば...

- 「この本に関する記事書いたよ!リンクして!」
- 「このサイト内にタイポがあったよ」
- 「こういう情報もサイトでサポートしてくれるとうれしいなぁ」etc...

私たちが対応できる範囲ではありますが，がんばっていきたいと思います。窓口としては...

GitHubのissueから

: [本サイトのGitHubリポジトリにあるissue](https://github.com/kazutan/DBDA2E-ja/issues)よりお問い合わせいただくと，一番早くかつスムーズに対応できます。
なお，ここでの質問はGitHubの性質上webでオープンとなりますので，その点はご了承ください。

Pull Requestで

: 簡単なタイポなどでしたら，[本リポジトリ](https://github.com/kazutan/DBDA2E-ja)をcloneして修正し，プルリクとして提案していただけると助かります。  
もちろん修正や大幅な改訂についてもプルリクは受け付けますが，管理サイドで内容をレビューし，必ずしもそのまま反映されると限らないことをご了承ください。

その他

: 書籍の内容に関するお問い合わせと同様，TwitterやMailなどでも受け付けております。どうぞよろしくお願いいたします。

## 本サイトコンテンツの著作について

可愛らしい犬の画像，および書籍内の文章につきましては，無断転載等はしないでください。コード等については設置しているリンク先の許諾に従ってください。

なお，本サイト独自のコンテンツ(解説など)につきましては，[CC-BY](https://creativecommons.org/licenses/by/4.0/legalcode.ja)にて公開するものとします。

## 本サイトの構築について

本サイトは，Rおよびrmarkdownパッケージをベースとして構築しております。使用しているライブラリなどについては以下のshowボタンをクリックしてください。

### {.showhide}

```{r}
sessionInfo()
```



