---
title-prefix: "ベイズ統計モデリング-R,JAGS,Stanによるチュートリアル- 原著第2版 サポートサイト"
pagetitle: "コードについて"
output:
  html_document:
    toc: false
---

最終更新: `r format(Sys.time(),'%Y/%m/%d')`

## 本書で登場するコードおよびデータについて

### ファイルの設置場所

本書で登場するRスクリプト及びデータファイルについては、原典のサポートサイトに設置してあります:

[Software, with programs for book - Doing Bayesian Data Analysis](https://sites.google.com/site/doingbayesiandataanalysis/software-installation)

上記リンク先の5.にあるリンク、もしくはページ末にあるところから、**DBDA2Eprograms.zip**という圧縮ファイルをダウンロードし、適宜展開してください。

### スクリプトの使用方法

本書に詳しく記載してあるので、ぜひ該当箇所を参照してください。不明な点やうまく動かないなどありましたら、遠慮なくお問い合わせください。お問い合わせにつきましては、[こちら](about.html#contact)を参考にしてください。

## Rの使い方について

本書では、コーディングに関して原典に従って翻訳して記載しています。ただ最近のR界隈を鑑みるに、違和感など感じる読者もいるかと思います。ここでは監訳するにあたって、監訳担当の前田が気になった点について、いくつかコメントを記しておきたいと思います。

### コーディング規約

本書ではキャメルケースを推奨・採用しており、その理由も書籍内に記述しておりますし、他にもコーディング規約に関する記述がいくつかあります。しかしながらコーディング規約については自分もしくは組織環境に沿ったケースでいいかと思います。

**個人的にはHadley Wickham氏がまとめている[The tidyverse style guide](http://style.tidyverse.org/)を参考にすることが多い**です。ぜひ一読されることをおすすめします。

### RStudioの機能について

本書ではRを使うのにRStudioを推奨しています。RStudioはRの統合環境として非常に強力で、現在非常に大きなシェアを有しています。また開発も活発で日々新しい機能が追加されたり修正されたりしています。

しかしながら本書ではRStudioについて十分に説明しきれていないと感じました。そこで最低限このあたりは知っていたほうがいいという機能について、極々簡単に紹介します。なお、以下はこれを執筆している時点(2017/08/21)での安定版である`v1.0.143`を前提とします。

#### Project機能

RStudioには**Project**という機能があり、一連の処理を行うためにデータやRスクリプトなどをまとめて管理できるという機能があります。このプロジェクトを活用することにより、

- 作業ディレクトリがプロジェクトのディレクトリとなる(いちいち気にしなくていい)
- プロジェクトごとに設定が可能
- バージョン管理、ビルド機能などが使える

などが利用できるようになります。RStudioを利用する上でほぼ必須となる機能です。

本書を読み進めて行く際には、**ぜひ本書をテストしていくためのProjectを準備**してから進めていくことをおすすめします。プロジェクトの使い方に関しては、本書の3章担当が過去に公開した以下のスライドの終盤を参照してください:

[Rの導入とRStudio事始め(改訂版)](https://www.slideshare.net/TakashiYamane1/rrstudio)

#### コード補完

RStudioには強力なコード補完機能が備わっており、Tabキーを押すだけで簡単に使えます。特に**本書では非常に似たRスクリプトファイルや関数がたくさんあります**。通常通りのて入力では大変苦労するはずです。そこでコード補完機能により、少しでもその負担を軽減することをおすすめします。コード補完機能については以下の記事に詳しくまとめております:

[RStudioのコード補完をもっと使ってみよう - Qiita](http://qiita.com/kazutan/items/4be49fbacb8c3d6c0f44)

#### 各種ボタンの活用

よく「Rはコマンドですべてしないといけないからつらい」と言われます。それはそれで重要なのですが、RStudioには各種様々なボタンやメニューが用意されており、グラフィカルな操作ができます。

非常に多くのボタンがあるので網羅するのは大変ですが、以下にRStudioが提供するチートシート(pdfファイル)があります。ぜひ一度見てみてはいかがでしょうか:

[RStudio IDE Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf)(pdfファイル)
